import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

export interface TemplateInfo {
  id: string;
  name: string;
  description: string;
  format: string;
  locale: 'zh-CN' | 'en-US' | 'both';
  source: string;
  /** true for user-added templates */
  custom?: boolean;
}

const businessReport: TemplateInfo = {
  id: 'business-report',
  name: '商务报告',
  description: '适合季度/年度商务报告，含封面、目录、章节、总结',
  format: 'html',
  locale: 'both',
  source: `<!DOCTYPE html>
<html lang="{{#if (eq locale "zh-CN")}}zh{{else}}en{{/if}}">
<head><meta charset="utf-8"/><style>
body { font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #333; line-height: 1.6; }
h1 { color: #1a365d; border-bottom: 3px solid #2b6cb0; padding-bottom: 12px; font-size: 28px; }
h2 { color: #2b6cb0; margin-top: 32px; font-size: 20px; }
.cover { text-align: center; padding: 60px 0; border-bottom: 2px solid #e2e8f0; margin-bottom: 40px; }
.cover h1 { border-bottom: none; font-size: 36px; }
.cover .subtitle { color: #718096; font-size: 16px; margin-top: 8px; }
.cover .date { color: #a0aec0; margin-top: 20px; }
.section { margin-bottom: 28px; }
.summary { background: #f7fafc; border-left: 4px solid #2b6cb0; padding: 16px 20px; margin: 20px 0; }
table { width: 100%; border-collapse: collapse; margin: 16px 0; }
th { background: #2b6cb0; color: white; padding: 10px 14px; text-align: left; }
td { padding: 10px 14px; border-bottom: 1px solid #e2e8f0; }
tr:nth-child(even) { background: #f7fafc; }
footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #a0aec0; font-size: 12px; text-align: center; }
</style></head>
<body>
<div class="cover">
  <h1>{{title}}</h1>
  {{#if subtitle}}<div class="subtitle">{{subtitle}}</div>{{/if}}
  {{#if author}}<div class="date">{{author}}</div>{{/if}}
  <div class="date">{{date}}</div>
</div>
{{#each sections}}
<div class="section">
  <h2>{{title}}</h2>
  <p>{{content}}</p>
  {{#if highlights}}
  <div class="summary">
    <strong>{{#if (eq ../locale "zh-CN")}}要点{{else}}Key Points{{/if}}:</strong>
    <ul>{{#each highlights}}<li>{{this}}</li>{{/each}}</ul>
  </div>
  {{/if}}
</div>
{{/each}}
<footer>{{#if (eq locale "zh-CN")}}由 AutoOffice 生成{{else}}Generated by AutoOffice{{/if}}</footer>
</body></html>`,
};

const academicPaper: TemplateInfo = {
  id: 'academic-paper',
  name: '学术论文',
  description: '适合学术论文、研究报告，含摘要、正文、参考文献',
  format: 'html',
  locale: 'both',
  source: `<!DOCTYPE html>
<html><head><meta charset="utf-8"/><style>
body { font-family: 'Times New Roman', Georgia, serif; max-width: 700px; margin: 0 auto; padding: 40px 20px; color: #222; line-height: 1.8; font-size: 14px; }
h1 { text-align: center; font-size: 22px; margin-bottom: 4px; }
.authors { text-align: center; color: #555; margin-bottom: 20px; }
.abstract { background: #fafafa; border: 1px solid #ddd; padding: 16px; margin: 20px 0; font-size: 13px; }
.abstract h3 { margin-top: 0; }
h2 { font-size: 16px; margin-top: 28px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
.references { font-size: 12px; }
.references li { margin-bottom: 6px; }
</style></head>
<body>
<h1>{{title}}</h1>
<div class="authors">{{#if authors}}{{#each authors}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}{{/if}}</div>
{{#if abstract}}
<div class="abstract"><h3>Abstract</h3><p>{{abstract}}</p></div>
{{/if}}
{{#each sections}}
<h2>{{@index}}. {{title}}</h2>
<p>{{content}}</p>
{{/each}}
{{#if references}}
<h2>References</h2>
<ol class="references">{{#each references}}<li>{{this}}</li>{{/each}}</ol>
{{/if}}
</body></html>`,
};

const simpleSlides: TemplateInfo = {
  id: 'simple-slides',
  name: '简约幻灯片',
  description: '适合演讲用的简洁大字幻灯片风格',
  format: 'html',
  locale: 'both',
  source: `<!DOCTYPE html>
<html><head><meta charset="utf-8"/><style>
body { font-family: -apple-system, sans-serif; margin: 0; padding: 0; }
.slide { min-height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center; padding: 40px; text-align: center; border-bottom: 1px solid #eee; }
.slide:nth-child(odd) { background: #f8f9fa; }
.slide h2 { font-size: 36px; color: #1a1a2e; margin-bottom: 20px; }
.slide p { font-size: 20px; color: #555; max-width: 600px; }
.slide ul { list-style: none; padding: 0; font-size: 18px; color: #444; }
.slide li { margin: 10px 0; }
.slide li::before { content: '→ '; color: #2b6cb0; }
</style></head>
<body>
{{#each sections}}
<div class="slide">
  <h2>{{title}}</h2>
  <p>{{content}}</p>
  {{#if points}}<ul>{{#each points}}<li>{{this}}</li>{{/each}}</ul>{{/if}}
</div>
{{/each}}
</body></html>`,
};

const techBrief: TemplateInfo = {
  id: 'tech-brief',
  name: '技术简报',
  description: '适合技术方案评审、架构决策记录、技术周报等场景',
  format: 'html',
  locale: 'both',
  source: `<!DOCTYPE html>
<html><head><meta charset="utf-8"/><style>
body { font-family: 'SF Mono', 'Fira Code', 'Consolas', monospace; max-width: 780px; margin: 0 auto; padding: 40px 20px; color: #1a1a2e; line-height: 1.7; background: #fafbfc; }
h1 { font-size: 24px; border-left: 4px solid #0969da; padding-left: 16px; margin-bottom: 8px; }
h2 { font-size: 17px; color: #0969da; margin-top: 28px; }
.meta { color: #656d76; font-size: 13px; margin-bottom: 24px; border-bottom: 1px solid #d0d7de; padding-bottom: 12px; }
.section { margin-bottom: 24px; }
.callout { background: #ddf4ff; border: 1px solid #54aeff; border-radius: 6px; padding: 12px 16px; margin: 16px 0; font-size: 14px; }
.callout.warn { background: #fff8c5; border-color: #d4a72c; }
code { background: #eff1f3; padding: 2px 6px; border-radius: 4px; font-size: 13px; }
pre { background: #161b22; color: #c9d1d9; padding: 16px; border-radius: 8px; overflow-x: auto; font-size: 13px; }
table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 14px; }
th { background: #f6f8fa; padding: 8px 12px; text-align: left; border: 1px solid #d0d7de; }
td { padding: 8px 12px; border: 1px solid #d0d7de; }
</style></head>
<body>
<h1>{{title}}</h1>
<div class="meta">{{#if author}}{{author}} · {{/if}}{{date}}{{#if version}} · v{{version}}{{/if}}</div>
{{#if summary}}<div class="callout">{{summary}}</div>{{/if}}
{{#each sections}}
<div class="section">
  <h2>{{title}}</h2>
  <p>{{content}}</p>
  {{#if code}}<pre><code>{{code}}</code></pre>{{/if}}
  {{#if decision}}<div class="callout warn"><strong>Decision:</strong> {{decision}}</div>{{/if}}
</div>
{{/each}}
</body></html>`,
};

const dashboardReport: TemplateInfo = {
  id: 'dashboard-report',
  name: '数据仪表盘',
  description: '适合数据分析、KPI 汇报、运营周报等数据密集型场景',
  format: 'html',
  locale: 'both',
  source: `<!DOCTYPE html>
<html><head><meta charset="utf-8"/><style>
body { font-family: -apple-system, 'Segoe UI', sans-serif; max-width: 960px; margin: 0 auto; padding: 32px 20px; color: #1f2937; background: #f3f4f6; }
h1 { font-size: 26px; font-weight: 700; margin-bottom: 4px; }
.subtitle { color: #6b7280; margin-bottom: 24px; }
.metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin-bottom: 32px; }
.metric-card { background: white; border-radius: 12px; padding: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
.metric-value { font-size: 32px; font-weight: 700; color: #2563eb; }
.metric-label { font-size: 13px; color: #6b7280; margin-top: 4px; }
.metric-delta { font-size: 12px; margin-top: 2px; }
.metric-delta.up { color: #16a34a; }
.metric-delta.down { color: #dc2626; }
.section-card { background: white; border-radius: 12px; padding: 24px; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
h2 { font-size: 18px; margin-top: 0; }
table { width: 100%; border-collapse: collapse; }
th { text-align: left; padding: 10px 12px; border-bottom: 2px solid #e5e7eb; color: #6b7280; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; }
td { padding: 10px 12px; border-bottom: 1px solid #f3f4f6; }
ul { padding-left: 20px; }
li { margin: 6px 0; }
</style></head>
<body>
<h1>{{title}}</h1>
<div class="subtitle">{{#if subtitle}}{{subtitle}}{{/if}} {{date}}</div>
{{#if metrics}}
<div class="metrics">
  {{#each metrics}}
  <div class="metric-card">
    <div class="metric-value">{{value}}</div>
    <div class="metric-label">{{label}}</div>
    {{#if delta}}<div class="metric-delta {{#if (eq direction 'up')}}up{{else}}down{{/if}}">{{delta}}</div>{{/if}}
  </div>
  {{/each}}
</div>
{{/if}}
{{#each sections}}
<div class="section-card">
  <h2>{{title}}</h2>
  <p>{{content}}</p>
  {{#if items}}<ul>{{#each items}}<li>{{this}}</li>{{/each}}</ul>{{/if}}
</div>
{{/each}}
</body></html>`,
};

const minimalLetter: TemplateInfo = {
  id: 'minimal-letter',
  name: '极简公函',
  description: '适合通知、公告、邀请函等正式但简洁的文档',
  format: 'html',
  locale: 'both',
  source: `<!DOCTYPE html>
<html><head><meta charset="utf-8"/><style>
body { font-family: Georgia, 'Noto Serif SC', serif; max-width: 640px; margin: 60px auto; padding: 0 24px; color: #222; line-height: 1.8; }
.header { text-align: right; color: #666; font-size: 14px; margin-bottom: 40px; }
.recipient { margin-bottom: 24px; }
h1 { font-size: 22px; text-align: center; margin: 32px 0; letter-spacing: 0.1em; }
p { text-indent: 2em; margin: 12px 0; }
.signature { margin-top: 48px; text-align: right; }
.signature .name { font-weight: bold; }
.signature .org { color: #666; font-size: 14px; }
</style></head>
<body>
<div class="header">{{date}}</div>
{{#if recipient}}<div class="recipient">{{recipient}}</div>{{/if}}
<h1>{{title}}</h1>
{{#each sections}}
<p>{{content}}</p>
{{/each}}
{{#if signature}}
<div class="signature">
  <div class="name">{{signature.name}}</div>
  {{#if signature.org}}<div class="org">{{signature.org}}</div>{{/if}}
</div>
{{/if}}
</body></html>`,
};

const BUILTIN_GALLERY: TemplateInfo[] = [businessReport, academicPaper, simpleSlides, techBrief, dashboardReport, minimalLetter];

function customTemplatesDir(): string {
  const dir = join(homedir(), '.autooffice', 'templates');
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  return dir;
}

function loadCustomTemplates(): TemplateInfo[] {
  const dir = customTemplatesDir();
  const results: TemplateInfo[] = [];
  try {
    for (const file of readdirSync(dir).filter((f) => f.endsWith('.json'))) {
      try {
        const raw = JSON.parse(readFileSync(join(dir, file), 'utf-8'));
        if (raw.id && raw.name && raw.source) {
          results.push({ ...raw, custom: true });
        }
      } catch { /* skip malformed files */ }
    }
  } catch { /* dir read error */ }
  return results;
}

function allTemplates(): TemplateInfo[] {
  return [...BUILTIN_GALLERY, ...loadCustomTemplates()];
}

export function listTemplates(): TemplateInfo[] {
  return allTemplates().map(({ source: _, ...rest }) => ({ ...rest, source: '' }));
}

export function getTemplate(id: string): TemplateInfo | undefined {
  return allTemplates().find((t) => t.id === id);
}

export function getTemplateSource(id: string): string | undefined {
  return allTemplates().find((t) => t.id === id)?.source;
}

export interface AddTemplateInput {
  id: string;
  name: string;
  description: string;
  format: string;
  locale?: 'zh-CN' | 'en-US' | 'both';
  source: string;
}

export function addCustomTemplate(input: AddTemplateInput): TemplateInfo {
  const existing = allTemplates();
  if (existing.some((t) => t.id === input.id)) {
    throw new Error(`Template id already exists: ${input.id}`);
  }
  if (!input.source.trim()) throw new Error('Template source cannot be empty');

  const tpl: TemplateInfo = {
    id: input.id,
    name: input.name,
    description: input.description,
    format: input.format,
    locale: input.locale ?? 'both',
    source: input.source,
    custom: true,
  };
  const dir = customTemplatesDir();
  writeFileSync(join(dir, `${input.id}.json`), JSON.stringify(tpl, null, 2), 'utf-8');
  return tpl;
}

export function updateCustomTemplate(id: string, patch: Partial<Omit<AddTemplateInput, 'id'>>): TemplateInfo {
  const dir = customTemplatesDir();
  const filePath = join(dir, `${id}.json`);
  if (!existsSync(filePath)) throw new Error(`Custom template not found: ${id}`);

  const existing: TemplateInfo = JSON.parse(readFileSync(filePath, 'utf-8'));
  const updated: TemplateInfo = {
    ...existing,
    ...(patch.name !== undefined ? { name: patch.name } : {}),
    ...(patch.description !== undefined ? { description: patch.description } : {}),
    ...(patch.format !== undefined ? { format: patch.format } : {}),
    ...(patch.locale !== undefined ? { locale: patch.locale } : {}),
    ...(patch.source !== undefined ? { source: patch.source } : {}),
    custom: true,
  };
  writeFileSync(filePath, JSON.stringify(updated, null, 2), 'utf-8');
  return updated;
}

export function deleteCustomTemplate(id: string): boolean {
  const dir = customTemplatesDir();
  const filePath = join(dir, `${id}.json`);
  if (!existsSync(filePath)) return false;
  unlinkSync(filePath);
  return true;
}
